name: scripts
channels:
    - conda-forge
dependencies:
    - python
    - polars
    - pandas
    - jinja2
    - rich
    - loguru
    - typer>=0.7
    # dev
    - pyink
    - isort
    - pylint
    - mypy
    - ruff
