name: Scripts
channels:
    - conda-forge
    - defaults
dependencies:
    - pandas
    - jinja2
    - rich
    - loguru
    - click
    # dev
    - yapf
    - toml
    - isort
    - pylint
    - mypy
