name: scripts
channels:
  - conda-forge
dependencies:
  - python
  - polars
  - pandas
  - jinja2
  - ffmpeg-normalize
  - rich
  - loguru
  - typer>=0.7
  # dev
  - pylint
  - mypy
  - ruff
  - typos
