[tool.pyink]
pyink-use-majority-quotes = true

[tool.isort]
profile = 'black'

[tool.ruff]
select = ['F', 'E', 'W', 'C90', 'N', 'D', 'UP', 'B', 'C4', 'RET', 'SIM', 'ERA', 'PD', 'PL', 'RUF']
ignore = ['D100', 'D101', 'D102', 'D103', 'D104', 'D105', 'D106', 'D107']
per-file-ignores = { '__init__.py' = ['F401'] }

[tool.ruff.pydocstyle]
convention = 'numpy'

[tool.pylint.messages_control]
disable = [
    'fixme',
    'import-error',
    'invalid-name',
    'missing-class-docstring',
    'missing-function-docstring',
    'missing-module-docstring',
    'redefined-outer-name',
    'too-few-public-methods',
    'too-many-arguments',
    'trailing-whitespace',
    'unused-argument',
    'unused-import',
    'unused-variable',
    'wrong-import-order',
]

[tool.mypy]
disable_error_code = ['var-annotated', 'import']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true
