[tool.pyink]
pyink-use-majority-quotes = true
preview = true

[tool.isort]
profile = 'black'

[tool.ruff]
select = ['ALL']
ignore = ['ANN', 'COM', 'D', 'PD901', 'S101', 'S603']
ignore-init-module-imports = true

[tool.ruff.flake8-bugbear]
extend-immutable-calls = ['typer.Argument', 'typer.Option']

[tool.ruff.flake8-quotes]
inline-quotes = 'single'

[tool.pylint.messages_control]
disable = [
    'fixme',
    'import-error',
    'invalid-name',
    'missing-class-docstring',
    'missing-function-docstring',
    'missing-module-docstring',
    'redefined-outer-name',
    'too-few-public-methods',
    'too-many-arguments',
    'trailing-whitespace',
    'unused-argument',
    'unused-import',
    'unused-variable',
    'wrong-import-order',
]

[tool.mypy]
disable_error_code = ['var-annotated', 'import']
check_untyped_defs = true
warn_unused_ignores = true
warn_unused_configs = true
